name: Test Checks

on:
  pull_request:
    paths-ignore: [.vscode/**, .github/**]
    branches: [ test ]

jobs:

  # Checks that the Angular app passes all defined unit tests
  unit-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Installing dependencies
      run: npm ci

    - name: Running all unit tests
      run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

  # Checks that the Angular app passes all defined end-to-end
  e2e-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Installing dependencies
      run: npm ci

    - name: Running all e2e tests
      run: npm run e2e -- --no-watch --no-progress --browsers=ChromeHeadlessCI

