# name: Test Checks

# on:
#   pull_request:
#     paths-ignore: [.vscode/**, .github/**]
#     branches: [ test ]

# jobs:

#   # Checks that the Angular app passes all defined end-to-end
#   e2e-test:
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2

#     - name: Installing dependencies
#       run: npm ci
#       env:
#         NODE_AUTH_TOKEN: ${{ secrets.TYLER_GITHUB_PACKAGES_TOKEN }}

#     - name: Running all e2e tests
#       run: npm run e2e -- --no-watch --no-progress --browsers=ChromeHeadlessCI

